// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using colectare_deseuri.Data;

#nullable disable

namespace colectare_deseuri.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250402152842_AdaugaCoordonateLaColectare")]
    partial class AdaugaCoordonateLaColectare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("colectare_deseuri.Models.Cetatean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cetateni");
                });

            modelBuilder.Entity("colectare_deseuri.Models.Colectare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPubela")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("PubelaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimpRidicare")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PubelaId");

                    b.ToTable("Colectari");
                });

            modelBuilder.Entity("colectare_deseuri.Models.Pubela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pubele");
                });

            modelBuilder.Entity("colectare_deseuri.Models.PubelaCetatean", b =>
                {
                    b.Property<int>("IdPubela")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCetatean")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPubela", "IdCetatean");

                    b.HasIndex("IdCetatean");

                    b.ToTable("PubeleCetateni");
                });

            modelBuilder.Entity("colectare_deseuri.Models.Colectare", b =>
                {
                    b.HasOne("colectare_deseuri.Models.Pubela", "Pubela")
                        .WithMany("Colectari")
                        .HasForeignKey("PubelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pubela");
                });

            modelBuilder.Entity("colectare_deseuri.Models.PubelaCetatean", b =>
                {
                    b.HasOne("colectare_deseuri.Models.Cetatean", "Cetatean")
                        .WithMany("PubeleCetateni")
                        .HasForeignKey("IdCetatean")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("colectare_deseuri.Models.Pubela", "Pubela")
                        .WithMany("PubeleCetateni")
                        .HasForeignKey("IdPubela")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cetatean");

                    b.Navigation("Pubela");
                });

            modelBuilder.Entity("colectare_deseuri.Models.Cetatean", b =>
                {
                    b.Navigation("PubeleCetateni");
                });

            modelBuilder.Entity("colectare_deseuri.Models.Pubela", b =>
                {
                    b.Navigation("Colectari");

                    b.Navigation("PubeleCetateni");
                });
#pragma warning restore 612, 618
        }
    }
}
